#/usr/bin/env sh

svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonDatasets/trunk ApiCommonDatasets
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonModel/trunk ApiCommonModel
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonPresenters/trunk ApiCommonPresenters
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonWebService/trunk ApiCommonWebService
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonWebsite/trunk ApiCommonWebsite
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/CBIL/trunk CBIL
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ClinEpiDatasets/trunk ClinEpiDatasets
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ClinEpiModel/trunk ClinEpiModel
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ClinEpiPresenters/trunk ClinEpiPresenters
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/ClinEpiWebsite/trunk ClinEpiWebsite
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/DJob/trunk DJob
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/EbrcModelCommon/trunk EbrcModelCommon
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/EbrcWebSvcCommon/trunk EbrcWebSvcCommon
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/EbrcWebsiteCommon/trunk EbrcWebsiteCommon
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/FgpUtil/trunk FgpUtil
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/GBrowse/trunk GBrowse
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/MicrobiomeDatasets/trunk MicrobiomeDatasets
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/MicrobiomeModel/trunk MicrobiomeModel
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/MicrobiomePresenters/trunk MicrobiomePresenters
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/MicrobiomeWebsite/trunk MicrobiomeWebsite
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/OrthoMCLModel/trunk OrthoMCLModel
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/OrthoMCLWebService/trunk OrthoMCLWebService
svn co https://cbilsvn.pmacs.upenn.edu/svn/apidb/OrthoMCLWebsite/trunk OrthoMCLWebsite
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/ReFlow/trunk ReFlow
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/TuningManager/trunk TuningManager
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/WDK/trunk WDK
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/WSF/trunk WSF
svn co https://cbilsvn.pmacs.upenn.edu/svn/gus/install/trunk install
